services:

    postgres-service:
        image: postgres
        ports:
            - "5432:5432"        
        environment:
            POSTGRES_PASSWORD: postgres
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5   

    pgadmin-service:
      image: dpage/pgadmin4
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: serg@psoftware.ru
        PGADMIN_DEFAULT_PASSWORD: 1
      ports:
        - "80:80"

    db-service:
        build: ./db
        depends_on:
            postgres-service:
                condition: service_healthy
        environment:
            - spring.datasource.url=jdbc:postgresql://postgres-service:5432/postgres
            - spring.datasource.username=postgres
            - spring.datasource.password=postgres

    artemis-service-lan:
        image:  apache/activemq-artemis:latest-alpine
        ports:
            - "6161:61616"
            - "8161:8161"
        healthcheck:
            test: ["CMD", "./bin/artemis", "check", "node", "--user=artemis", "--password=artemis"]
            start_period: 10s
            interval: 5s
            timeout: 5s
            retries: 5

    artemis-service-prcs:
        image:  apache/activemq-artemis:latest-alpine
        ports:
            - "6162:61616"
            - "8162:8161"
        healthcheck:
            test: ["CMD", "./bin/artemis", "check", "node", "--user=artemis", "--password=artemis"]
            start_period: 10s
            interval: 5s
            timeout: 5s
            retries: 5

    consumer-service:
        build: ./aggregator
        depends_on:
            artemis-service-lan:
                condition: service_healthy
            artemis-service-prcs:
                condition: service_healthy
            postgres-service:
                condition: service_healthy                
        environment:
            - app.artemis.lan.url=tcp://artemis-service-lan:61616
            - app.artemis.lan.username=artemis
            - app.artemis.lan.password=artemis
            - app.artemis.lan.queue=MT
            - app.artemis.lan.batchsize=5000
            - app.artemis.prcs.url=tcp://artemis-service-prcs:61616
            - app.artemis.prcs.username=artemis
            - app.artemis.prcs.password=artemis
            - app.artemis.prcs.queue=ED            
            - spring.datasource.url=jdbc:postgresql://postgres-service:5432/postgres
            - spring.datasource.username=postgres
            - spring.datasource.password=postgres          

    producer-service:
        build: ./producer
        depends_on:
            artemis-service-lan:
                condition: service_healthy
            postgres-service:
                condition: service_healthy                
        environment:
            - app.serviceToStart=producer
            - app.artemis.url=tcp://artemis-service-lan:61616
            - app.artemis.username=artemis
            - app.artemis.password=artemis
            - app.artemis.queue=MT
            - app.artemis.batchsize=1000


