services:

    postgres-service:
        image: postgres
        ports:
            - "5432:5432"        
        environment:
            POSTGRES_PASSWORD: postgres
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5   

    pgadmin-service:
      image: dpage/pgadmin4
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: serg@psoftware.ru
        PGADMIN_DEFAULT_PASSWORD: 1
      ports:
        - "80:80"

    artemis-service:
        image:  apache/activemq-artemis:latest-alpine
        ports:
            - "6161:61616"
            - "8161:8161"
        healthcheck:
            test: ["CMD", "./bin/artemis", "check", "node", "--user=artemis", "--password=artemis"]
            start_period: 10s
            interval: 5s
            timeout: 5s
            retries: 5

    db-service:
        build: ../db
        depends_on:
            postgres-service:
                condition: service_healthy
        environment:
            - spring.datasource.url=jdbc:postgresql://postgres-service:5432/postgres
            - spring.datasource.username=postgres
            - spring.datasource.password=postgres
